# This is a basic workflow to help you get started with Actions

name: install-qt

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  QT_VER: 5.15.2
  QT_TARGET: desktop

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  install-qt-macos:
  
    runs-on: macos-11

    env:
      QT_ARCH: clang_64
      QT_HOST: mac

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3 
        with:
          version: ${{ env.QT_VER }}
          host: ${{ env.QT_HOST }}
          target: ${{ env.QT_TARGET }}
          arch: ${{ env.QT_ARCH }}
          dir: ${{ env.RUNNER_WORKSPACE }}
          cache: true
          cache-key-prefix: install-qt-action

      - name: Check qmake
        shell: bash
        run: |
          which qmake
          qmake --version

      - name: Check cmake
        shell: bash
        run: |
          which cmake
          cmake --version
          cmake --help

      - name: List files
        shell: bash
        run: ls -lR ${RUNNER_WORKSPACE}
        
  install-qt-ubuntu:
  
    runs-on: ubuntu-20.04

    env:
      QT_ARCH: gcc_64
      QT_HOST: linux

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3 
        with:
          version: ${{ env.QT_VER }}
          host: ${{ env.QT_HOST }}
          target: ${{ env.QT_TARGET }}
          arch: ${{ env.QT_ARCH }}
          dir: ${{ env.RUNNER_WORKSPACE }}
          cache: true
          cache-key-prefix: install-qt-action

      - name: Check qmake
        shell: bash
        run: |
          which qmake
          qmake --version

      - name: Check cmake
        shell: bash
        run: |
          which cmake
          cmake --version
          cmake --help

      - name: List files
        shell: bash
        run: ls -lR ${RUNNER_WORKSPACE}

  install-qt-windows:
    
    runs-on: windows-2019

    env:
      QT_ARCH: win64_msvc2019_64
      QT_HOST: windows

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3 
        with:
          version: ${{ env.QT_VER }}
          host: ${{ env.QT_HOST }}
          target: ${{ env.QT_TARGET }}
          arch: ${{ env.QT_ARCH }}
          dir: ${{ env.RUNNER_WORKSPACE }}
          cache: true
          cache-key-prefix: install-qt-action

      - name: Check qmake
        shell: bash
        run: |
          which qmake
          qmake --version

      - name: Check cmake
        shell: bash
        run: |
          which cmake
          cmake --version
          cmake --help

      - name: List files
        shell: bash
        run: ls -lR ${RUNNER_WORKSPACE}
