# This is a basic workflow to help you get started with Actions

name: install-qt

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  install-qt-macos:
  
    runs-on: macos-11

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3 
        with:
          version: '5.15.2'
          host: 'mac'
          target: 'desktop'
          arch: 'clang_64'
          dir: ${{ github.workspace }}
          cache: true
          cache-key-prefix: ${{ runner.os }}-install-qt-action

      - name: Check qmake
        run: which qmake

      - name: Check cmake
        run: |
          which cmake
          cmake --version

      - name: List files
        run: ls -lR ${{ github.workspace }}
        
  install-qt-ubuntu:
  
    runs-on: ubuntu-20.04

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3 
        with:
          version: '5.15.2'
          host: 'linux'
          target: 'desktop'
          arch: 'gcc_64'
          dir: ${{ github.workspace }}
          cache: true
          cache-key-prefix: ${{ runner.os }}-install-qt-action

      - name: Check qmake
        run: which qmake

      - name: Check cmake
        run: |
          which cmake
          cmake --version

      - name: List files
        run: ls -lR ${{ github.workspace }}

  install-qt-windows:
  
    runs-on: windows-2019

    steps:
      - name: Install Qt
        uses: jurplel/install-qt-action@v3 
        with:
          version: '5.15.2'
          host: 'windows'
          target: 'desktop'
          arch: 'win64_msvc2019_64'
          dir: 'C:/'
          cache: true
          cache-key-prefix: ${{ runner.os }}-install-qt-action

      - name: Check qmake
        run: Get-Command qmake

      - name: Check cmake
        run: |
          Get-Command cmake
          cmake --version

      - name: List files
        run: Get-ChildItem -Recurse C:/Qt
